//! Auto-generated by `datalink_shim_sqlite_dynlink_emit::emit_dynlink`
//! (Phase A, opaque-blob scalar dispatch). Do NOT edit by hand — regenerate.
#![allow(unused_imports, dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "bridge",
        generate_all,
    });
}

use bindings::exports::sqlite::extension::metadata::{
    Guest as MetadataGuest, Manifest, ScalarFunctionSpec,
};
use bindings::exports::sqlite::extension::scalar_function::Guest as ScalarFunctionGuest;
use bindings::exports::sqlite::extension::aggregate_function::Guest as AggregateGuest;
use bindings::exports::sqlite::extension::metadata::AggregateFunctionSpec;
use bindings::exports::sqlite::extension::vtab::{Guest as VtabGuest, IndexInfo, IndexPlan, VtabRow};
use bindings::exports::sqlite::extension::metadata::VtabSpec;
use bindings::sqlite::extension::types::{FunctionFlags, SqlValue};

use bindings::compose::dynlink::linker;

const PROVIDER_ID: &str = "timescale_toolkit-composed";
const EXTENSION_ROOT: &str = "timescale";
const CATALOG_EXTENSION: &str = "timescaledb";
const CATALOG_VERSION: &str = "2.19.0";

fn resolve() -> Result<linker::Instance, String> {
    linker::resolve_by_id(&PROVIDER_ID.to_string())
        .map_err(|e| format!("dynlink resolve('{}'): {:?}", PROVIDER_ID, e))
}

// -----------------------------------------------------------
// CBOR envelope (mirrors provider crate's Request/Response).
// -----------------------------------------------------------

#[derive(Debug, Clone)]
enum CborValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<CborValue>),
}

impl serde::Serialize for CborValue {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        match self {
            CborValue::Null => s.serialize_unit(),
            CborValue::Bool(b) => s.serialize_bool(*b),
            CborValue::Int(i) => s.serialize_i64(*i),
            CborValue::Float(f) => s.serialize_f64(*f),
            CborValue::Text(t) => s.serialize_str(t),
            CborValue::Bytes(b) => s.serialize_bytes(b),
            CborValue::List(items) => {
                use serde::ser::SerializeSeq;
                let mut seq = s.serialize_seq(Some(items.len()))?;
                for item in items {
                    seq.serialize_element(item)?;
                }
                seq.end()
            }
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
struct Request {
    #[serde(rename = "v")]
    version: u32,
    args: Vec<CborValue>,
}

#[derive(Debug, Clone, serde::Deserialize)]
struct Response {
    #[serde(default)]
    ok: Option<ResponseValue>,
    #[serde(default)]
    err: Option<String>,
}

#[derive(Debug, Clone)]
enum ResponseValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<ResponseValue>),
}

impl<'de> serde::Deserialize<'de> for ResponseValue {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{Error, MapAccess, SeqAccess, Visitor};
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = ResponseValue;
            fn expecting(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
                f.write_str("a CBOR value (null, bool, int, float, text, bytes, list)")
            }
            fn visit_unit<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_none<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_bool<E: Error>(self, v: bool) -> Result<ResponseValue, E> { Ok(ResponseValue::Bool(v)) }
            fn visit_i64<E: Error>(self, v: i64) -> Result<ResponseValue, E> { Ok(ResponseValue::Int(v)) }
            fn visit_u64<E: Error>(self, v: u64) -> Result<ResponseValue, E> {
                if v <= i64::MAX as u64 { Ok(ResponseValue::Int(v as i64)) }
                else { Err(E::custom("u64 overflow to i64")) }
            }
            fn visit_f64<E: Error>(self, v: f64) -> Result<ResponseValue, E> { Ok(ResponseValue::Float(v)) }
            fn visit_str<E: Error>(self, v: &str) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v.to_string())) }
            fn visit_string<E: Error>(self, v: String) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v)) }
            fn visit_bytes<E: Error>(self, v: &[u8]) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v.to_vec())) }
            fn visit_byte_buf<E: Error>(self, v: Vec<u8>) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v)) }
            fn visit_seq<A: SeqAccess<'de>>(self, mut s: A) -> Result<ResponseValue, A::Error> {
                let mut items = Vec::new();
                while let Some(v) = s.next_element::<ResponseValue>()? { items.push(v); }
                Ok(ResponseValue::List(items))
            }
            fn visit_map<A: MapAccess<'de>>(self, mut m: A) -> Result<ResponseValue, A::Error> {
                let k: Option<String> = m.next_key()?;
                let k = k.ok_or_else(|| A::Error::custom("empty map"))?;
                let v = match k.as_str() {
                    "Null" => { let _: serde::de::IgnoredAny = m.next_value()?; ResponseValue::Null }
                    "Bool" => ResponseValue::Bool(m.next_value()?),
                    "Int"  => ResponseValue::Int(m.next_value()?),
                    "Float" => ResponseValue::Float(m.next_value()?),
                    "Text" => ResponseValue::Text(m.next_value()?),
                    "Bytes" => {
                        let b: serde_bytes::ByteBuf = m.next_value()?;
                        ResponseValue::Bytes(b.into_vec())
                    }
                    "List" => ResponseValue::List(m.next_value()?),
                    other => return Err(A::Error::custom(format!("unknown tag: {}", other))),
                };
                Ok(v)
            }
        }
        d.deserialize_any(V)
    }
}

fn encode_request(args: Vec<CborValue>) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    ciborium::into_writer(&Request { version: 1, args }, &mut out)
        .map_err(|e| format!("cbor encode: {}", e))?;
    Ok(out)
}

fn decode_response(bytes: &[u8]) -> Result<Response, String> {
    ciborium::from_reader(bytes).map_err(|e| format!("cbor decode: {}", e))
}

fn call(method: &str, args: Vec<CborValue>) -> Result<ResponseValue, String> {
    let inst = resolve()?;
    let payload = encode_request(args)?;
    let bytes = inst
        .invoke(&method.to_string(), &payload)
        .map_err(|e| format!("{}: invoke: {:?}", method, e))?;
    let resp = decode_response(&bytes)?;
    if let Some(err) = resp.err {
        return Err(format!("{}: {}", method, err));
    }
    Ok(resp.ok.unwrap_or(ResponseValue::Null))
}

// -----------------------------------------------------------
// SqlValue marshalling — variant discipline per the @1.0.0
// contract. The `wit-value` arm is Phase-A-out-of-scope; the
// bridge treats it as null in both directions.
// -----------------------------------------------------------

fn sqlv_to_cbor(v: &SqlValue) -> Result<CborValue, String> {
    Ok(match v {
        SqlValue::Null => CborValue::Null,
        SqlValue::Integer(i) => CborValue::Int(*i),
        SqlValue::Real(f) => CborValue::Float(*f),
        SqlValue::Text(t) => CborValue::Text(t.clone()),
        SqlValue::Blob(b) => CborValue::Bytes(b.clone()),
        // WitValue is Phase-A-out-of-scope. Prior code silently
        // downgraded it to CBOR null, which lied to the provider
        // (an explicit-typed argument became indistinguishable
        // from a real NULL). Surface an explicit error instead so
        // callers see a diagnostic on the SQL side.
        SqlValue::WitValue(_) => {
            return Err("bridge: WitValue arg not supported in dynlink Phase A".to_string());
        }
    })
}

fn response_to_sqlv(v: ResponseValue) -> Result<SqlValue, String> {
    Ok(match v {
        ResponseValue::Null => SqlValue::Null,
        ResponseValue::Bool(b) => SqlValue::Integer(if b { 1 } else { 0 }),
        ResponseValue::Int(i) => SqlValue::Integer(i),
        ResponseValue::Float(f) => SqlValue::Real(f),
        ResponseValue::Text(t) => SqlValue::Text(t),
        ResponseValue::Bytes(b) => SqlValue::Blob(b),
        // A list-shaped response has no SQLite scalar sqlvalue
        // arm. Prior code silently returned SqlValue::Null, hiding
        // a shape mismatch behind an implicit NULL. Return an
        // explicit error so the SQL side sees a diagnostic.
        ResponseValue::List(_) => {
            return Err("bridge: list-shaped response not supported".to_string());
        }
    })
}

fn scalar_name_by_id(id: u64) -> Option<&'static str> {
    match id {
        1 => Some("asap_smooth"),
        2 => Some("asof"),
        3 => Some("into_array"),
        4 => Some("lttb"),
        5 => Some("saturating_add"),
        6 => Some("saturating_add_pos"),
        7 => Some("saturating_mul"),
        8 => Some("saturating_sub"),
        9 => Some("saturating_sub_pos"),
        10 => Some("to_plotly"),
        11 => Some("to_text"),
        12 => Some("toolkit_pipeline_support"),
        13 => Some("trim_to"),
        _ => None,
    }
}

/// SQL-name aliasing: translate a compact-form SQL name (e.g.
/// `st_geomfromtext`) to its WIT-canonical (long) form
/// (`st_geom_from_text`) before kebab-casing to the provider
/// method name. The catalog carries both spellings as scalars in
/// `leaf.scalars` (both are advertised via `metadata.describe()`
/// so callers can use either), and as first-class `[[aliases]]`
/// entries. The provider dispatch only matches the WIT-canonical
/// form; the bridge's per-row `call` calls `canonical_for(name)`
/// so both spellings route to the same provider arm.
fn canonical_for(name: &str) -> &str {
    match name {
        other => other,
    }
}

// -----------------------------------------------------------
// Guest impls.
// -----------------------------------------------------------

struct Component;

impl MetadataGuest for Component {
    fn describe() -> Manifest {
        let scalar_functions: Vec<ScalarFunctionSpec> = vec![
            ScalarFunctionSpec {
                id: 1,
                name: "asap_smooth".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 2,
                name: "asof".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 3,
                name: "into_array".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 4,
                name: "lttb".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 5,
                name: "saturating_add".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 6,
                name: "saturating_add_pos".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 7,
                name: "saturating_mul".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 8,
                name: "saturating_sub".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 9,
                name: "saturating_sub_pos".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 10,
                name: "to_plotly".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 11,
                name: "to_text".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 12,
                name: "toolkit_pipeline_support".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
            ScalarFunctionSpec {
                id: 13,
                name: "trim_to".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::DETERMINISTIC,
            },
        ];
        let aggregate_functions: Vec<AggregateFunctionSpec> = vec![
            AggregateFunctionSpec {
                id: 1000000,
                name: "asap_smooth".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::empty(),
                is_window: false,
            },
            AggregateFunctionSpec {
                id: 1000001,
                name: "gp_lttb".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::empty(),
                is_window: false,
            },
            AggregateFunctionSpec {
                id: 1000002,
                name: "lttb".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::empty(),
                is_window: false,
            },
            AggregateFunctionSpec {
                id: 1000003,
                name: "timevector".to_string(),
                num_args: -1,
                func_flags: FunctionFlags::empty(),
                is_window: false,
            },
        ];
        let vtabs: Vec<VtabSpec> = vec![
            VtabSpec {
                id: 2000000,
                name: "into_values".to_string(),
                eponymous: true,
                mutable: false,
                batched: false,
            },
            VtabSpec {
                id: 2000001,
                name: "unnest".to_string(),
                eponymous: true,
                mutable: false,
                batched: false,
            },
        ];
        Manifest {
            name: EXTENSION_ROOT.to_string(),
            version: CATALOG_VERSION.to_string(),
            scalar_functions,
            aggregate_functions,
            collations: vec![],
            vtabs,
            dot_commands: vec![],
            has_authorizer: false,
            has_update_hook: false,
            has_commit_hook: false,
            has_wal_hook: false,
            wal_hook_id: 0,
            declared_capabilities: vec![],
            optional_capabilities: vec![],
            preferred_prefix: None,
            prefix_expansion: None,
            typed_values: vec![],
        }
    }
}

impl ScalarFunctionGuest for Component {
    fn call(func_id: u64, args: Vec<SqlValue>) -> Result<SqlValue, String> {
        let name = scalar_name_by_id(func_id)
            .ok_or_else(|| format!("unknown function id {}", func_id))?;
        // SQL-style null propagation. Providers that need to
        // observe explicit NULL arguments will need a follow-up
        // Phase to opt in per-arm.
        if args.iter().any(|v| matches!(v, SqlValue::Null)) {
            return Ok(SqlValue::Null);
        }
        // Alias translation: SQL name → WIT-canonical → provider
        // method (kebab-case). Compact-form SQL names (e.g.
        // `st_geomfromtext`) route through `canonical_for` to their
        // long form (`st_geom_from_text`) before kebab-casing;
        // non-alias names pass through unchanged. See
        // `canonical_for` above.
        let canonical = canonical_for(name);
        let method = canonical.replace('_', "-");
        let cbor_args: Vec<CborValue> = args
            .iter()
            .map(sqlv_to_cbor)
            .collect::<Result<Vec<_>, String>>()?;
        let resp = call(&method, cbor_args)?;
        response_to_sqlv(resp)
    }
}


fn aggregate_name_by_id(id: u64) -> Option<&'static str> {
    match id {
        1000000 => Some("asap_smooth"),
        1000001 => Some("gp_lttb"),
        1000002 => Some("lttb"),
        1000003 => Some("timevector"),
        _ => None,
    }
}

fn agg_accumulator() -> &'static std::sync::Mutex<std::collections::HashMap<u64, Vec<CborValue>>> {
    static M: std::sync::OnceLock<std::sync::Mutex<std::collections::HashMap<u64, Vec<CborValue>>>> = std::sync::OnceLock::new();
    M.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

fn aggregate_method_for(func_id: u64, suffix: &str) -> Result<String, String> {
    let name = aggregate_name_by_id(func_id)
        .ok_or_else(|| format!("unknown aggregate id {}", func_id))?;
    let canonical = canonical_for(name);
    // Provider method naming convention: `<kebab-name>-<suffix>`
    // where suffix is one of `step` (unused — step accumulates
    // locally), `finalize`, `value`, or `inverse`. The provider
    // owns the aggregate semantics; the bridge is a pure CBOR
    // tunnel that ships the accumulated per-row args in one shot.
    Ok(format!("{}-{}", canonical.replace('_', "-"), suffix))
}

impl AggregateGuest for Component {
    fn step(func_id: u64, context_id: u64, args: Vec<SqlValue>) -> Result<(), String> {
        // SQL-aggregate NULL-row semantics: any NULL contribution
        // is skipped (mirrors sqlite3's built-in count(*)/sum()).
        if args.iter().any(|v| matches!(v, SqlValue::Null)) {
            return Ok(());
        }
        let _ = aggregate_name_by_id(func_id)
            .ok_or_else(|| format!("unknown aggregate id {}", func_id))?;
        let cbor_args: Vec<CborValue> = args
            .iter()
            .map(sqlv_to_cbor)
            .collect::<Result<Vec<_>, String>>()?;
        agg_accumulator()
            .lock()
            .expect("aggregate accumulator mutex poisoned")
            .entry(context_id)
            .or_insert_with(Vec::new)
            .push(CborValue::List(cbor_args));
        Ok(())
    }

    fn finalize(func_id: u64, context_id: u64) -> Result<SqlValue, String> {
        let method = aggregate_method_for(func_id, "finalize")?;
        let rows = agg_accumulator()
            .lock()
            .expect("aggregate accumulator mutex poisoned")
            .remove(&context_id)
            .unwrap_or_default();
        // Empty aggregation → NULL per SQL semantics (sum() over 0
        // rows is NULL, etc.). Providers that want a domain-specific
        // zero can encode it in their finalize handler.
        if rows.is_empty() {
            return Ok(SqlValue::Null);
        }
        let resp = call(&method, vec![CborValue::List(rows)])?;
        response_to_sqlv(resp)
    }

    fn value(func_id: u64, context_id: u64) -> Result<SqlValue, String> {
        let method = aggregate_method_for(func_id, "value")?;
        let rows = agg_accumulator()
            .lock()
            .expect("aggregate accumulator mutex poisoned")
            .get(&context_id)
            .cloned()
            .unwrap_or_default();
        if rows.is_empty() {
            return Ok(SqlValue::Null);
        }
        let resp = call(&method, vec![CborValue::List(rows)])?;
        response_to_sqlv(resp)
    }

    fn inverse(func_id: u64, context_id: u64, _args: Vec<SqlValue>) -> Result<(), String> {
        let _ = aggregate_name_by_id(func_id)
            .ok_or_else(|| format!("unknown aggregate id {}", func_id))?;
        agg_accumulator()
            .lock()
            .expect("aggregate accumulator mutex poisoned")
            .entry(context_id)
            .and_modify(|v| { v.pop(); });
        Ok(())
    }
}


fn vtab_name_by_id(id: u64) -> Option<&'static str> {
    match id {
        2000000 => Some("into_values"),
        2000001 => Some("unnest"),
        _ => None,
    }
}

// Per-cursor state: buffered result rows + current position.
// Keyed by (vtab_id, cursor_id) since cursor ids may collide
// across vtabs in the host's per-instance allocation strategy.
fn cursor_state()
    -> &'static std::sync::Mutex<std::collections::HashMap<(u64, u64), (Vec<Vec<u8>>, usize)>>
{
    static M: std::sync::OnceLock<std::sync::Mutex<std::collections::HashMap<(u64, u64), (Vec<Vec<u8>>, usize)>>> = std::sync::OnceLock::new();
    M.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

impl VtabGuest for Component {
    fn create(
        vtab_id: u64,
        instance_id: u64,
        db_name: String,
        table_name: String,
        args: Vec<String>,
    ) -> Result<String, String> {
        // Eponymous vtabs (which is all we advertise) see only
        // connect(). Fall through so a caller who does hit create()
        // gets the same schema.
        <Self as VtabGuest>::connect(vtab_id, instance_id, db_name, table_name, args)
    }

    fn connect(
        vtab_id: u64,
        _instance_id: u64,
        _db_name: String,
        _table_name: String,
        _args: Vec<String>,
    ) -> Result<String, String> {
        let _ = vtab_name_by_id(vtab_id)
            .ok_or_else(|| format!("unknown vtab id {}", vtab_id))?;
        // Single-column BLOB schema. Hidden `_arg0` matches the
        // table-valued-function call form `f(g1)` — the query
        // planner binds the argv slot through xBestIndex.
        Ok("CREATE TABLE x(\"result\" BLOB, \"_arg0\" HIDDEN)".to_string())
    }

    fn destroy(_vtab_id: u64, _instance_id: u64) -> Result<(), String> { Ok(()) }
    fn disconnect(_vtab_id: u64, _instance_id: u64) -> Result<(), String> { Ok(()) }

    fn best_index(_vtab_id: u64, _instance_id: u64, info: IndexInfo) -> Result<IndexPlan, String> {
        use bindings::exports::sqlite::extension::vtab::ConstraintUsage;
        let mut next_argv_idx: i32 = 1;
        let constraint_usage = info
            .constraints
            .iter()
            .map(|c| {
                if c.usable {
                    let ci = ConstraintUsage { argv_index: next_argv_idx, omit: true };
                    next_argv_idx += 1;
                    ci
                } else {
                    ConstraintUsage { argv_index: 0, omit: false }
                }
            })
            .collect();
        Ok(IndexPlan {
            constraint_usage,
            idx_num: 0,
            idx_str: None,
            estimated_cost: 1.0,
            estimated_rows: 100,
            orderby_consumed: false,
        })
    }

    fn open(_vtab_id: u64, _instance_id: u64, _cursor_id: u64) -> Result<(), String> { Ok(()) }

    fn close(vtab_id: u64, cursor_id: u64) -> Result<(), String> {
        cursor_state()
            .lock()
            .expect("vtab cursor state mutex poisoned")
            .remove(&(vtab_id, cursor_id));
        Ok(())
    }

    fn filter(
        vtab_id: u64,
        cursor_id: u64,
        _idx_num: i32,
        _idx_str: Option<String>,
        args: Vec<SqlValue>,
    ) -> Result<(), String> {
        let name = vtab_name_by_id(vtab_id)
            .ok_or_else(|| format!("unknown vtab id {}", vtab_id))?;
        let canonical = canonical_for(name);
        let method = canonical.replace('_', "-");
        let cbor_args: Vec<CborValue> = args
            .iter()
            .map(sqlv_to_cbor)
            .collect::<Result<Vec<_>, String>>()?;
        let resp = call(&method, cbor_args)?;
        // Response shape: List of Bytes (one blob per row). Any
        // other shape → single-row wrapper (best-effort).
        let rows: Vec<Vec<u8>> = match resp {
            ResponseValue::List(items) => items
                .into_iter()
                .map(|item| match item {
                    ResponseValue::Bytes(b) => b,
                    ResponseValue::Null => Vec::new(),
                    other => {
                        // Non-blob row → serialise as CBOR so callers
                        // still see a byte payload.
                        let mut out = Vec::new();
                        let _ = ciborium::into_writer(&response_value_to_cbor(other), &mut out);
                        out
                    }
                })
                .collect(),
            ResponseValue::Null => Vec::new(),
            other => {
                let mut out = Vec::new();
                let _ = ciborium::into_writer(&response_value_to_cbor(other), &mut out);
                vec![out]
            }
        };
        cursor_state()
            .lock()
            .expect("vtab cursor state mutex poisoned")
            .insert((vtab_id, cursor_id), (rows, 0));
        Ok(())
    }

    fn next(vtab_id: u64, cursor_id: u64) -> Result<(), String> {
        let mut guard = cursor_state()
            .lock()
            .expect("vtab cursor state mutex poisoned");
        if let Some((_, pos)) = guard.get_mut(&(vtab_id, cursor_id)) {
            *pos += 1;
        }
        Ok(())
    }

    fn eof(vtab_id: u64, cursor_id: u64) -> bool {
        let guard = cursor_state()
            .lock()
            .expect("vtab cursor state mutex poisoned");
        match guard.get(&(vtab_id, cursor_id)) {
            Some((rows, pos)) => *pos >= rows.len(),
            None => true,
        }
    }

    fn column(vtab_id: u64, cursor_id: u64, col: i32) -> Result<SqlValue, String> {
        let guard = cursor_state()
            .lock()
            .expect("vtab cursor state mutex poisoned");
        let (rows, pos) = guard
            .get(&(vtab_id, cursor_id))
            .ok_or_else(|| format!("no cursor state for vtab {}/cursor {}", vtab_id, cursor_id))?;
        if *pos >= rows.len() {
            return Err("column past EOF".to_string());
        }
        // Column 0 = result BLOB; hidden columns (>=1) round-trip
        // the argv back as-is (the query planner already bound them).
        if col == 0 {
            Ok(SqlValue::Blob(rows[*pos].clone()))
        } else {
            Ok(SqlValue::Null)
        }
    }

    fn rowid(vtab_id: u64, cursor_id: u64) -> Result<i64, String> {
        let guard = cursor_state()
            .lock()
            .expect("vtab cursor state mutex poisoned");
        let (_, pos) = guard
            .get(&(vtab_id, cursor_id))
            .ok_or_else(|| format!("no cursor state for vtab {}/cursor {}", vtab_id, cursor_id))?;
        Ok(*pos as i64)
    }

    fn fetch_batch(
        _vtab_id: u64,
        _cursor_id: u64,
        _max_rows: u32,
    ) -> Result<Vec<VtabRow>, String> {
        // Per-vtab opt-in via `vtab-spec.batched = true`. This
        // bridge advertises `batched: false` for every vtab so the
        // host never routes here — return the sentinel error the
        // host's cli trampoline probes for.
        Err("not implemented".to_string())
    }
}

fn response_value_to_cbor(v: ResponseValue) -> CborValue {
    match v {
        ResponseValue::Null => CborValue::Null,
        ResponseValue::Bool(b) => CborValue::Bool(b),
        ResponseValue::Int(i) => CborValue::Int(i),
        ResponseValue::Float(f) => CborValue::Float(f),
        ResponseValue::Text(t) => CborValue::Text(t),
        ResponseValue::Bytes(b) => CborValue::Bytes(b),
        ResponseValue::List(items) => CborValue::List(
            items.into_iter().map(response_value_to_cbor).collect(),
        ),
    }
}

bindings::export!(Component with_types_in bindings);
